kubernetes-sigs/cloud-provider-equinix-metal

deploy/releases/README.md, go.mod, packet/cloud.go, packet/devices.go, packet/facilities.go
Adds some debugging options, which remain off by default, but are enabled by `--v=<level>`, plus docs for how to use it.
=> Add optional debugging and docs

README.md, deploy/releases/v1.0.0/deployment.yaml, deploy/template/secret.yaml, main.go, packet/cloud.go, packet/cloud_test.go
Fixes #22 
**Do not merge until [WIP] is removed.**
This is a first run. There still are some changes to be made, but they depend on #31 being merged first. I will remove `[WIP]` and comment that it is ready, when you can merge it in.
This PR aligns secrets with how [csi-packet](https://github.com/packethost/csi-packet) does it, allowing a single secret to serve both. It will be our standard going forward.
When this is done, the api key and project ID can be in one of either of the following two places (aligned with CSI):
* env vars, as per the current implementation
* a secrets file in json structure
Eventually, we will allow it to dynamically monitor the secrets file and update if it changes.
What is left to complete this:
=> Support secrets from file to align with CSI

README.md
If secret was copied as-is, without comma, Packet CCM would be stuck
in a crash loop:
provider config error: failed to process json of configuration file at
path /etc/cloud-sa/cloud-sa.json: invalid character '"' after object
key:value pair
Signed-off-by: Martin Polednik <m.polednik@gmail.com>
=> README.md: add missing comma to secret example

packet/devices.go, packet/devices_test.go, packet/facilities_test.go
Previously, we were returning `<uuid>` when it should be `packet://<uuid>`. This was messing up other areas.
Fixed the issue, and the test.
Fixes #37 
I am running some additional tests; please do not merge in until I do.
=> ensure InstanceID returns correctly formatted providerID

README.md, go.mod, go.sum, main.go, packet/bgp.go, packet/cloud.go, packet/constants.go, packet/loadbalancers.go
Fixes #39 
Sets BGP annotations on the nodes. Whenever a node comes up, it extracts the BGP peer IP, and sets the local and peer ASNs as annotations on the kubernetes node object. Also updates the README.
* The ASNs are 6500 and 65530, per the Packet docs, but can be overridden
* The annotations are `packet.com/node.asn`, `packet.com/peer.asns`, `packet.com/peer.ips`, but can be overridden
=> add bgp annotations to nodes

Makefile, README.md, go.mod, go.sum, lb/manifests.yaml, main.go, packet/bgp.go, packet/cloud.go, packet/loadbalancers.go, packet/metallb/configmap.go, packet/metallb/configmap_test.go, util/manifests.go
This largish PR does the following:
* enables load balancers using metallb by default on Packet CCM. It can be disabled by option, as listed in the README [here](https://github.com/packethost/packet-ccm#load-balancers)
* ensures it all syncs correctly
* adds a `make fmt` command that formats the files
* updates the README doc for running locally (usually during development) with the manifests
=> enable metallb

Makefile, packet/cloud.go, packet/version.go
_Originally from https://github.com/packethost/packet-ccm/pull/56#issuecomment-655528837_
This PR adds packet.VERSION and uses this in the packngo.UserAgent.  The Makefile was already applying the version at build time, but it was referencing a missing version variable (which we now have).
Closes #54
=> add VERSION and apply this to the UserAgent

README.md, deploy/releases/v1.0.1/deployment.yaml
Originally from https://github.com/packethost/packet-ccm/pull/56#issuecomment-655528837
This adds the missing chart for the v1.0.1 release and updates the README.md to reflect this as the latest version.
=> add missing v1.0.1 release yaml

Dockerfile, README.md, main.go
This does a few things:
* includes the metallb manifests in the docker image
* sets the default path in the binary for the manifests to `lb/manifests.yaml`
* updates the README to correctly explain how to use it
=> include manifests in docker image

README.md
This adds the following badges to the README.md:
[![GitHub release](https://img.shields.io/github/release/packethost/packet-ccm/all.svg?style=flat-square)](https://github.com/packethost/packet-ccm/releases)
[![Go Report Card](https://goreportcard.com/badge/github.com/packethost/packet-ccm)](https://goreportcard.com/report/github.com/packethost/packet-ccm)
[![Docker Pulls](https://img.shields.io/docker/pulls/packethost/packet-ccm.svg)](https://hub.docker.com/r/packethost/packet-ccm/)
[![Slack](https://slack.packet.com/badge.svg)](https://slack.packet.com)
[![Twitter Follow](https://img.shields.io/twitter/follow/packethost.svg?style=social&label=Follow)](https://twitter.com/intent/follow?screen_name=packethost&user_id=788180534543339520)
Of note, there have not been any releases yet. …
=> add README.md badges for code quality, CI, releases, pulls, and social

.github/workflows/ci.yaml, .github/workflows/release.yaml
The prior workflow as far as docker hub was concerned was:
* for all pushes to master (PR merges or tags): build the images and push them out
* for tag pushes (releases): build the images, push them out, then pull+tag/with/semver+push
This was wasteful; this is no reason to go through the entire build cycle, if the images already exist for that commit. If they do not, we should not be building anyways, but failing.
This changes it as follows:
* for all pushes to master _not including tags_: build the images and push them out
* for tag pushes: pull/tag/push
The release creation and artifacts are unchanged.
=> Do not build for releases, only tag existing images

.gitignore, README.md, go.mod, go.sum, packet/eip_controlplane_reconciliation.go
This enables CCM to ensure that traffic to a control plane node with an enabled EIP is managed by that node, without having to do any work on the node.
Thus, you do not need to add the EIP to a local interface, or add a routing rule, or remove it when shutting down, or worry about timing.
=> Manage ip via svc

packet/bgp.go
Fixes #69 
We always just created the BGP enablement at the project level, because it was idempotent. Turns out, it isn't. This should fix it.
=> check if project has BGP session before trying to create it

packet/devices.go, packet/devices_test.go
Fixes #73 
This fixes it. Before, it was
```yaml
node.kubernetes.io/instance-type: baremetal_0
topology.kubernetes.io/region: ewr1
```
with this, it is
```yaml
node.kubernetes.io/instance-type: t1.small.x86
topology.kubernetes.io/region: ewr1
```
=> sending wrong plan name

deploy/template/deployment.yaml
Without access to configmaps, it could not set up metallb properly.
These access rights really should be restricted a little better, but for now, let's fix this real user's problem, and then worry about it.
=> ensure CCM has access to configmaps

util/manifests.go
We were losing errors that occurred when trying to apply the metallb manifests. In a case where permissions were off (or anything else), nothing showed up in the logs.
This fixes that.
=> handle manifest errors correctly

packet/bgp.go, packet/loadbalancers.go
Fixes #63 
Adds all peers to the metallb configmap, and also to the annotations. Annotations are sorted and comma-separated for consistency.
=> add multiple peers

packet/loadbalancers.go, packet/metallb/configmap.go
We had no logs at any level for when the loadbalancer reconciles nodes (adding them to the configmap). This adds those statements, mostly V(2) and V(5).
It also returns the error, which it should have done, but only return at the end of handling all of the nodes.
=> lots of logs on loadbalancer, plus return the error

packet/bgp.go, packet/cloud.go, packet/const.go, packet/eip_controlplane_reconciliation.go, packet/ipreservations.go, packet/ipreservations_test.go, packet/loadbalancers.go
Fixes #89 
We have an issue wherein this captures events as they happen, but if the ccm is down (e.g. pod restart or move), it won't actually do the correct deletes of nodes (from `peers`) or services (delete the EIP and remove from `pools` in configmap).
This fixes all of that by creating 3 modes for reconciliation functions:
* add: add whatever nodes/services it receives (idempotently, obviously)
* remove: remove whatever nodes/services it receives
* sync: take the provides list as authoritative, and make sure that the list of EIPs, peers and pools precisely matches that list
We already ran sync once per minute, but we didn't cover every use case.
=> have mode to sync everything

deploy/template/deployment.yaml, packet/cloud.go, packet/cloud_test.go
As per kubernetes/cloud-provider#12 the
ClusterID requirement was never really followed through on, so the
flag is probably going to be removed in the future.
See also
https://github.com/brandond/k3s/commit/e109f13382909f41f0377b3fcd4bcc340510266b
I tested this and I didn't notice any side-effects.
=> Add stub support for clusterID

README.md, main.go, packet/bgp.go, packet/cloud.go, packet/config.go
In some large clusters, one may want to have dedicated pool of Ingress
nodes, which will be handling ingress traffic. CCM currently enables BGP
on all nodes in the cluster.
Enabling BGP on all nodes in the cluster also has security implications,
as now every node can start running it's own BGP speaker and start
capturing incoming traffic.
This patch adds support for new configuration option called BGP Node
Selector, which allows specifying Kubernetes Label selector, which will
be used for filtering the nodes, which will have BGP enabled.
To preserve existing behavior, by default all Nodes are selected.
Closes #100
=> Add support for BGP node selector

README.md, main.go, packet/bgp.go, packet/cloud.go, packet/config.go, packet/constants.go, packet/eip_controlplane_reconciliation.go, packet/loadbalancers.go
We already set annotations for peer ASN, local ASN, and peer IPs. This adds an annotation for the src IP, so you know which IP to use to source the peering request.
It also:
* standardizes the default annotation names
* fixes an error message to make it clearer
=> src IP annotation

packet/config.go
We want to print `<masked>` when the auth token string is NOT empty.
cc: @deitch
=> Fix boolean logic in auth token debug info

README.md, packet/loadbalancers.go, packet/loadbalancers/kubevip/kubevip.go
This needs to be completed as follows.
* link to correct kube-vip documentation for configuring and consuming annotations, and using service IPs
* add any missing kube-vip support pieces
* ensure that kube-vip works correctly
=> add kube-vip loadbalancer option

README.md
This is the **beginning** of rebranding CCM from Packet -> Equinix Metal.
Thus far, it only covers the README, and does not implement everything the README says it does. This is intentional. I want us to agree on what this all should be by reviewing the README. When all are agreed, I will update the PR with actual implementation.
This makes some assumptions:
* all env vars that were `PACKET_*` become `METAL_*`, because `EQUINIXMETAL_` is a mouthful, very difficult to type correctly the first time, and an eyeball scan doesn't show you what the errors are
* config names are similarly renamed
* resources created inside Kubernetes that were named `packet-*` are renamed `metal-*`
* Kubernetes annotations places on nodes that were `packet.com/<something>` are now …
=> [WIP] rebrand

go.mod, go.sum, main.go, metal/bgp.go, metal/cloud.go, metal/devices.go, metal/eip_controlplane_reconciliation.go, metal/facilities.go, metal/loadbalancers.go, metal/loadbalancers/metallb/metallb.go
To fix switching log verbosity, as right now adding -v=10 has no effect.
Closes #143
=> Switch to klog v2

metal/cloud.go
To give it a change to retry initialization.
Workaround for #140.
=> metal: exit when service controller fails to initialize

metal/loadbalancers.go
Fixes #148 
Also adds logging when no loadbalancer is present, and always logs what kind of loadbalancer.
=> fix kube-vip scheme typo; better logging

Makefile
So multi-arch manifests can be also built locally, not only on CI.
One can now run:
```
make image-manifest-all-push BUILD_IMAGE=quay.io/foo/packet-ccm BUILD_TAG=bar
```
To build and push all required images, build the manifest and push it as well.
Closes #104.
=> Makefile: add targets for building multi-arch Docker manifests

Dockerfile
There have been intermittent build failures, known issues with certain `apk` commands on arm. These don't usually cause a major problem - just rerun the build job - but this helps keep it clean.
It is a good thing on its own merits, anyways.
=> bump alpine version

metal/cloud.go, metal/devices.go, metal/devices_test.go
Allows matching devices based on the old providerID convention (packet://).
This is to help enable migrating Cluster API-based clusters to newer versions of the CCM.
=> Add backward compatibility for providerID convention

README.md, metal/loadbalancers/metallb/metallb.go
There were 2 issues:
1. The README didn't make it clear that when providing config for a load balancer, you need to provide everything in path, not host, so, e.g. `metallb:///namespace/configname` and not `metallb://namespace/configname` (three slashes instead of two); fixes the doc
2. Fixes parsing of the above config information, and changes it to use `/` as a separator; `:` causes too many issues, and is un-URL-ish
=> fix handling of metallb custom configmap and document it

README.md, main.go, metal/bgp.go, metal/cloud.go, metal/config.go, metal/constants.go, metal/loadbalancers.go, metal/loadbalancers/empty/empty.go, metal/loadbalancers/interface.go, metal/loadbalancers/kubevip/kubevip.go, metal/loadbalancers/metallb/metallb.go, metal/loadbalancers/node.go
I am not done with testing this yet, but it is ready for eyes-on review.
This places the md5 password string, however it appears when getting device info from the Equinix Metal API, in a few places:
* an annotation, base64-encoded. This doesn't provide real security, but it is better than being able to see it at a glance.
* in the metallb configmap in the right place for the peer
It also adds supportive details:  an env var for configuring the annotation name, a default annotation name, documentation of the above.
It also cleans up the README a bit: removing a duplicate entry in the configuration table, and clarifies that the env var for local ASN and BGP password are solely for requesting it when enabling on the project; when actually setting it on nodes, it uses the ones retrieved from …
=> set md5 passphrase base64-encoded in annotations, add to metallb configmap

README.md, main.go, metal/config.go, metal/constants.go, metal/devices.go, metal/eip_controlplane_reconciliation.go
Fixes #171 
Affects only control plane EIP assignment.
Before this change:
* EIP port always is set to 443
* Healthchecks on EIP port defaults to 6443, able to override via env var `METAL_API_SERVER_PORT` (which always has to be set to match 443)
* Healthchecks on control plane nodes always check on port 6443, no matter what the kube-apiserver actually is listening on
After this change:
* EIP port is set via env var `METAL_API_SERVER_PORT`; if it is not set, or is `0`, use the same port as the `kube-apiserver`
* Healthchecks on EIP port match the previous line
* Healthchecks on control plane nodes are set to whatever port the `kube-apiserver` is listening on, determined by checking the Kubernetes service `default/kubernetes`
=> configure EIP port and healthcheck ports from existing service with env var override

README.md, metal/eip_controlplane_reconciliation.go, metal/loadbalancers.go
Fixes #174 
Ensures that the special `Service` for the control plane EIP does not try to get managed by the load balancer.
=> exempt controlplane Service from loadbalancer management

deploy/chart/templates/clusterrole.yaml, deploy/template/deployment.yaml
Permission to read and update events is needed for the CCM otherwise logs will show errors trying to read events when a new  LoadBalancer service has been created.
=> Add permission to read and update events

README.md, main.go
Naming-wise, this is way too close to MetalLB, one of the types of load balancers supported.
Fixes https://github.com/equinix/cloud-provider-equinix-metal/issues/184.
Includes some fixups before, see commit messages for details:
```
commit dbb06a0bd25269f06c153d9a3a5e5341e686f9f8
Author: Florian Klink <flokli@flokli.de>
Date:   Thu Jul 1 19:44:10 2021 +0200
rename METAL_LB to METAL_LOAD_BALANCER
Naming-wise, this is way too close to MetalLB, one of the types of load
balancers supported.
commit d7f6bedbd7aa0b8c817a0009c584910afde70649
Author: Florian Klink <flokli@flokli.de>
Date:   Thu Jul 1 19:40:21 2021 +0200
README: fix config key
It seems this setting has been called `loadbalancer`, not `metalLB`, at
least since 2b353398ccc8a09df7d4ceaa72f40397a49c495a.
commit …
```
=> rename METAL_LB to METAL_LOAD_BALANCER

README.md, deploy/chart/values.yaml, go.mod, go.sum, main.go, metal/cloud.go, metal/cloud_test.go, metal/config.go, metal/constants.go, metal/devices.go
In addition to the BGP annotations we already use. This came as an outgrowth of Gardener work, but I started seeing other potential use cases. In any case, the right place to do this is CPEM.
@displague I know this will cause you to have to rebase your big PR; sorry about that. this was getting in the way of some other work.
=> add annotation for private network

README.md, deploy/chart/values.yaml, metal/constants.go
Kubernetes annotations only support a single `/` in the key. The code as it stands right now emits the following error:
```
devices.go:307] instances.reconcileNodes(): failed to save updated node with annotations production-control-plane-1: Failed to patch node production-control-plane-1: Node "production-control-plane-1" is invalid: metadata.annotations: Invalid value: "metal.equinix.com/network/4/private": a qualified name must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]') with an optional DNS subdomain prefix and '/' (e.g. 'example.com/MyName')
```
I've replaced the subsequent `/` with `-`, as dashes are used …
=> fix: use format supported by Kubernetes annotations

deploy/chart/templates/deployment.yaml, deploy/template/deployment.yaml
The default value for `operator` is `Equal`, but this doesn't provide
any value to check against, causing this to not be scheduled on control
plane nodes with the following taint:
```
- effect: NoSchedule
key: node-role.kubernetes.io/master
value: "true"
```
Setting the operator to `Exists` will cause this to be scheduled.
cc @rawkode
=> Add missing operator: Exists to Deployment

metal/config.go
minute issue, but `%!s(MISSING)` is always printed here.
```
load balancer config: ''%!s(MISSING)
<whatever is configured>
```
=> wrong use of variadic

README.md, deploy/chart/values.yaml, go.mod, go.sum, main.go, metal/cloud.go, metal/cloud_test.go, metal/common_test.go, metal/config.go, metal/devices_test.go, metal/facilities_test.go, metal/loadbalancers.go
Explicitly uses an environment variable or config to set the metro, falling back to metadata. If both are specified, both are sent in the EIP creation request.
=> Add explicit metro support

Makefile, metal/cloud.go, metal/version.go
Fixes #142 
Works with the Kubernetes standard versioning (without all of the branch complexity)
=> report versions correctly

metal/bgp.go, metal/cloud.go, metal/eip_controlplane_reconciliation.go, metal/loadbalancers.go, metal/watchers.go
This has two commits.
The first restructures some of the files and funcs without changing any functionality. It just reduces duplicate code, makes it easier to understand, separates some things into their own file, etc.
The second cleans up the logging:
* do not return an error for something that isn't actually an error. If it is informative, log a message (at various log levels), but return `nil`
* if we have a non-fatal error in a loop, log the message, save the affected resource in a slice, and complete the loop. Only at the end should we return the error.
I have wanted to do this for a long time.
=> Clean logging

Makefile
We can use `-X "k8s.io/component-base/version/verflag.programName=Cloud Provider Equinix Metal"` to set a custom program name. This overrides the default of `Kubernetes`.
It makes more sense for `{ccm} --version` to say `Cloud Provider Equinix Metal v3.3.0` rather than `Kubernetes v3.3.0`.
This is a follow-up to the conversation in https://github.com/equinix/cloud-provider-equinix-metal/pull/221#discussion_r769741420
Related to https://github.com/equinix/cloud-provider-equinix-metal/issues/142
=> set programName rendered in `--version` output

README.md, metal/loadbalancers/metallb/config.go, metal/loadbalancers/metallb/metallb.go
As of version 0.11.0, metallb supports setting the source IP for the node. This leverages that, while declaring a minimum version.
=> support source IP from metallb

CONTRIBUTING.md
Fixes #218 
The DCO file is not present in this project. Use the external copy https://developercertificate.org/.  This URL is also used by probot, https://github.com/apps/dco.
Alternatives considered:
- add a copy of the DCO to this project
-- 
The DCO probot is actively scanning this repository.
>
=> use external copy of DCO in CONTRIBUTING.md

metal/devices.go
Devices contain "RootPassword" and other fields that may contain sensitive fields. Keep this data out of the logs.
=> do not log EM device objects which may contain sensitive fields

metal/bgp.go, metal/cloud.go, metal/cloud_test.go, metal/devices.go, metal/loadbalancers.go, metal/loadbalancers/empty/empty.go, metal/loadbalancers/interface.go, metal/loadbalancers/kubevip/kubevip.go, metal/loadbalancers/metallb/configmap.go, metal/loadbalancers/metallb/configmap_test.go, metal/loadbalancers/metallb/metallb.go, metal/loadbalancers/metallb/util_test.go, metal/watchers.go
This is a deep change in how CCM operates.
The CCM has listeners for changes to services and nodes, as well as a timer loop. Every time a node or service is added or removed, or a node is added or removed, it calls the `serviceReconciler` or `nodeReconciler` or each sub-service - bgp, loadbalancers, devices, facilities, control-plane-EIP. Some of these return `nil`, indicating "nothing to do".
The main ones that handle it are bgp and load balancer. 
* services: looks at the added service, filters for `type=LoadBalancer`, gets an EIP from EQXM if needed, and then calls the specific implementation of load balancer to add or remove it
* nodes: looks at the node, filters out for specific labels if provided, and then ensures bgp is enabled on the node, adds annotations, and tells the specific …
=> use standard API LoadBalancers

metal/cloud.go, metal/cloud_test.go, metal/devices_test.go
When trying to run with the load balancer disabled, currently the controller will panic, because we are testing if an interface is nil rather than if the value of the interface is nil).
Replacing the interface types in the cloud struct with the concrete types resolves the issue and as far as I can tell does not impact anything else.
=> Fix issue with services controller when load balancing should be disabled

.dockerignore, .github/dependabot.yml, .github/workflows/ci.yaml, .github/workflows/release.yaml, .golangci.yml, Dockerfile, Makefile, deploy/chart/values.yaml, deploy/template/deployment.yaml
- Add support for multiple registries
- conditionalize registry logins and image pushes
- add dockerignore
- Cleanup image creation
- bump golangci-lint
- use golangci-lint for vet, use golangci github action for lint
- Add caching for ci/release workflows
- breakout lint, test, image as separate jobs
- cleanup makefile a bit more
- Add dependabot config
- Skip ci workflow on dependabot branches
- Update default image used by helm chart and deployment.yaml
Signed-off-by: Jason DeTiberus <detiber@users.noreply.github.com>
=> Refactor test and release workflows

deploy/chart/templates/deployment.yaml, deploy/template/deployment.yaml
This PR adds a scheduling toleration for "node.kubernetes.io/not-ready". This is to enable the cloud provider to come up on the first control plane node of a brand new cluster and assign the EIP that will be used as the cluster's VIP for its API server. This behavior is needed for cluster-api style provisions without BGP.
=> Enable the CCM to come up before node is ready so it can assign EIP.

.github/actions/metadata/action.yaml, .github/workflows/ci.yaml, .github/workflows/release.yaml, CONTRIBUTING.md
Update automated workflow to allow for overriding orgs for dockerhub and quay
=> Update automated workflow to allow for overriding orgs for dockerhub and quay

README.md, metal/loadbalancers.go, metal/loadbalancers/empty/empty.go, metal/loadbalancers/interface.go, metal/loadbalancers/kubevip/kubevip.go, metal/loadbalancers/metallb/configmap.go, metal/loadbalancers/metallb/configmap_test.go, metal/loadbalancers/metallb/metallb.go, metal/loadbalancers/metallb/resource.go, metal/loadbalancers/metallb/util_test.go
fixes #247 
cc @displague @enkelprifti98
=> fix metallb matchlabels to be valid

Dockerfile
We call the builds by passing `--platforms` to the `docker buildx build`, whether directly or via the GitHub action `docker/build-push-action`.
Either way, this causes it to run every command under qemu, so that non-native builds take about 4-5x as long as the native ones. See a typical build and issue #257 .
This proposes to fix the biggest problem, i.e. those emulated builds. Instead of emulating the entire process, this will run the actual build (as well as `go mod download` and every other step except for image assembly) on the native platform, but cross-compiling.
Local tests show that the result is that building for both native and alternate platforms are within a few percentage points of each other. We will let CI run here and see what it reports.
=> use native go cross-compiling

.github/workflows/ci.yaml, .github/workflows/release.yaml
We were using the `QUAY_ORG` instead of the ghcr org (which, by definition, is the `repository_owner`), so no one could pull it down.
=> fix ghcr.io org name for releases

README.md
This reverts commit e69de27234b0675a17b7f45ef68e79ad3a4cc975 which was merged in #265 
Based on https://github.com/kubernetes/kubernetes/issues/110018 , the `--cloud-provider=none` will **not** be deprecated, as it is needed in order for the correct taint to be on the node, and the CCM to function properly.
=> Revert "document --cloud-provider args for 1.23+"

metal/cloud.go, metal/loadbalancers.go
Fixes #258 
When the control plane EIP is managed by CCM, it also creates a service of `type=LoadBalancer`. This makes sense. But it also causes the loadbalancer logic to trigger, adding it to any load balancers. This, in turn, can cause BGP to kick in.
The fix is to filter out the specific service for the control plane.
=> filter out controlplane EIP from loadbalancer services

metal/loadbalancers/metallb/metallb.go
Fixes #286 
We were including only the service name (without the namespace) when naming the address pool for metallb. This meant that if we created two services with the same name, but in different namespaces - which is completely legitimate from Kubernetes' perspective - only the first would work. The second would generate a metallb error.
This change includes the namespace and the name in metallb.
I ran tests, as well as went through the metallb code, and see no issues.
=> include namespace in metallb address-pool name

deploy/chart/templates/deployment.yaml, deploy/template/deployment.yaml
Partially addresses #304, specifically the second issue raised.
Rather than running it as a `Deployment` with `replicas=1`, we run this as a `DaemonSet` with `nodeAffinity` restricting it to control plane nodes. This means that if you have 3 such nodes, you will get 3 copies.
The built-in leader election of k8s.io/cloud-provider ensures that only one processes events at a time.
If you have multiple (as this provides), and one dies (of greater concern, the node it is running on dies, taking CPEM with it), then one of the remaining ones will take over quickly, and work will continue as normal. This includes the important part of letting the apiserver know that the node is gone, which is a CPEM responsibility.
**Important note::** This does _not_ solve the issue of the node that dies being …
=> switch to DaemonSet to run on all control plane nodes

deploy/chart/templates/clusterrole.yaml, deploy/chart/templates/deployment.yaml, deploy/template/deployment.yaml
For reasons lost in the mists of time, CPEM had `--leader-elect=false` on the its CLI flags. This disabled leader-elect.
This PR:
1. Sets it to `true`
2. Adds the necessary `ClusterRole` permissions
=> enable leader-elect

deploy/chart/templates/daemonset.yaml
Fixes #312 
I debated changing the `deploy/template/deployment.yaml` file as well, but that wasn't named for `Deployment` as much as "this contains all of the things to deploy, including RBAC and `Deployment` (now a `DaemonSet`) etc. So I left that one alone.
=> rename deployment.yaml to daemonset.yaml in Helm and remove extraneous field

README.md
metallb 0.13.x changes several things, to the point that CPEM doesn't work correctly with it.
This does **not** fix it, but does indicate in the README which versions are supported.
When we are ready to support it, we will update these comments.
=> metallb support range

.github/workflows/ci.yaml
Signed-off-by: Chris Privitere <23177737+cprivitere@users.noreply.github.com>
=> bump golangci-lint to 1.51 in ci

.github/actions/metadata/action.yaml
Same as #372 but for action.yaml which I overlooked before.
Our CI is using deprecated functionality for saving outputs. We need to convert to using environment files or our workflows will stop working later this year.
Details are here: 
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
Signed-off-by: Chris Privitere <23177737+cprivitere@users.noreply.github.com>
=> replace set-output with output environment file

.github/actions/metadata/action.yaml
The old version of the metadata-action relied on node.js:12 which is EOL and will be breaking soon.
Signed-off-by: Chris Privitere <23177737+cprivitere@users.noreply.github.com>
=> Bump metadata-action version

metal/cloud.go
Fix the load balancer ignoring the EIP facilicy selection annotation by actually passing the correct annotation configuration to the new load balancer function.
Fixes #409
=> fix: correctly use the eip facility annotation

deploy/template/deployment.yaml, go.mod, go.sum, main.go
Refactor of the main.go to be more in line with upstream examples.
Reference examples:
https://github.com/kubernetes/cloud-provider/blob/master/sample/basic_main.go
https://github.com/kubernetes/kubernetes/blob/master/cmd/cloud-controller-manager/main.go
- remove unnecessary random seeding
- register json logging library
- rename opts to ccmOptions like upstream
- update some comments
- remove no longer necessary pflag as well as flag normalization
- remove no longer necessary log init lines
- Use "cloud-provider-equinix-metal" for RBAC naming
=> refactor: cleanup of cpem

metal/loadbalancers.go
While introducing Equinix Metal Load Balancer support in CPEM, we updated the `EnsureLoadBalancer` function to return the result of `GetLoadBalancer` so that the code to return a LoadBalancerStatus for existing load balancers is in one place.
As a result of that consolidation, we uncovered an inconsistency in the two calculations of LoadBalancerStatus: the one in EnsureLoadBalancer created an Ingress with the load balancer IP, but the one in GetLoadBalancer created an Ingress with the load balancer CIDR, which is not valid.
This updates the GetLoadBalancer implementation to match the valid code that was previously in EnsureLoadBalancer.
=> fix: return a valid LoadBalancerStatus for BGP-based load balancers

metal/loadbalancers/emlb/infrastructure/manager.go
This updates the Equinix Metal Load Balancer integration to enable HTTP client debug logs when the `PACKNGO_DEBUG` environment variable is set.  In the future we may introduce other ways of enabling debug logs for the provider, but this change enables users to debug the EMLB parts of the provider using the same approach they use to debug the rest of the provider.
=> fix: hook the EMLB client up to our debug env var

BUILD.md, CONTRIBUTING.md, Makefile, README.md, SUPPORT.md, deploy/chart/Chart.yaml, go.mod, main.go, metal/cloud_test.go, metal/controlplane_load_balancer_manager.go, metal/loadbalancers.go, metal/loadbalancers/emlb/emlb.go, metal/loadbalancers/emlb/infrastructure/manager.go, metal/loadbalancers/empty/empty.go, metal/loadbalancers/kubevip/kubevip.go, metal/loadbalancers/metallb/metallb.go
- Moved the repo to github.com/kubernetes-sigs
- Update all references from equinix/cloud-provider-equinix-metal
to kubernetes-sigs/cloud-provider-equinix-metal
Part of #420
=> chore: update go module path

metal/bgp.go
This PR fixes a panic caused by using bgpConfig.Md5.Get() in situations where the MD5 hash isn't set. We use GetMd5() instead which checks for this for us.
=> :bug: avoid panic by using GetMd5() instead of Md5.Get

metal/cloud.go
The old packngo SDK had built-in support for enabling debug logging if the `PACKNGO_DEBUG` environment variable was set to any value.  The generated equinix-sdk-go SDK requires explicitly enabling debug logging in consumer code, so when we switched from `packngo` to `equinix-sdk-go` we lost support for the `PACKNGO_DEBUG` environment variable.  This updates CPEM to enable debug logging for `equinix-sdk-go` if the old `PACKNGO_DEBUG` environment variable is set.
Fixes #517
=> fix: enable equinix-sdk-go debugging when PACKNGO_DEBUG env var is set

metal/loadbalancers/emlb/emlb.go
Check if svc objects have no annotations and create a map to avoid a nil pointer reference. Inspired by: https://github.com/kubernetes-sigs/cluster-api/blob/v1.7.3/util/annotations/helpers.go
Fixes: #477
=> fix: handle svc objects with empty annotations

.github/actions/metadata/action.yaml
Bump the docker/metadata-action in our metadata action to v5.
We should refactor this repo's CI to be more like the cluster api provider packet CI. There is no reason to use this custom composite metadata action anymore.
=> chore(deps): Bump docker/metadata-action to v5
