kubernetes-sigs/cloud-provider-equinix-metal

- .travis.yml
- Makefile
- README.md
> Add travis.yml

- .travis.yml
Was missing settings on `make cd`
> fix cd vars

- README.md
- deploy/releases/README.md
- deploy/releases/v0.0.4/deployment.yaml
- deploy/releases/v0.0.4/secret.yaml
Add documentation for running v0.0.4 CCM on Kubernetes.
> Add README.md for release v0.0.4

- deploy/releases/v1.0.0/deployment.yaml
- deploy/releases/v1.0.0/secret.yaml
In preparation for the upcoming 1.0.0 release, this creates a `deploy/v1.0.0` directory, including changes necessary for it.
> Add v1.0.0 directory to prepare for v1.0.0; includes CLI switch

- .drone.yml
It wasn't finding the builds on merge to master
> add build step first

- .drone.yml
Sure hoping this one finally gets it.
> build step before image

- packet/bgp.go
- packet/loadbalancers.go
Uses the device bgp config from the packet API to retrieve the peer IP, rather than trying to figure it out from the device network interfaces.
Fixes (at least part of) #43, specifically [this comment](https://github.com/packethost/packet-ccm/issues/43#issuecomment-657941433).
> use actual packet device bgp endpoint to discover neighbour

- LICENSE
- OWNERS.md
- README.md
- SUPPORT.md
Also SUPPORT.md, OWNERS.md and several other issues raised in #72 . Once this one is in, we will have another PR for the rest.
> maintained and licensed

- CODE-OF-CONDUCT.md
- CONTRIBUTING.md
> add contributing and code of conduct

- deploy/template/deployment.yaml
- lb/manifests.yaml
Also added lots and lots of comments on the ClusterRole, so we can have some audit trail of what it is there for.
> update rbac to reflect actual requirementS

- deploy/template/deployment.yaml
Clusterrole initial apiGroup was not formatted correctly.
Signed-off-by: knrt10 <tripathi.kautilya@gmail.com>
> Format: deploy/template/deployment.yaml

- packet/metallb/configmap.go
> remove strict parsing

- packet/cloud.go
Just to make things easier for future reviewers.
> update documentation on controller lifecycle

- Makefile
> manifest-tool was failing with missing binder

- deploy/template/secret.yaml
> deploy/template/secret.yaml: fix JSON formatting

- README.md
> update version in README

- README.md
- packet/loadbalancers.go
Fixes #120 ; also describes it in detail in the README.
cc @c0dyhi11
> add tagging for unique clusters

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- Dockerfile
- Makefile
Massively simplifies Makefile on the way, and adds Makefile help via `make help`.
> switch the complex build and multi-arch to github actions

- README.md
Reverts packethost/packet-ccm#132
> Revert "[WIP] rebrand"

- .github/workflows/release.yaml
> login first

- metal/loadbalancers/metallb/metallb.go
> handle metallb configmap without config

- README.md
Fixes #160 
As discussed in #157 with @displague and @detiber , and requested by @enkelprifti98
> Clarify how to set configuration options

- metal/eip_controlplane_reconciliation.go
Due to how the healthcheck logic worked, it tried to do `rest.Body.Close()` even if `resp.Body` was `nil`. This ensures we only close if `err == nil && `resp.Body != nil`.
Thanks to @displague for figuring out the logic problem.
> handle error safely in healthcheck

- README.md
> add docs about BGP peers

- metal/devices.go
> fix bug when getting node private network

- README.md
This already worked, but never was documented.
> document bring-your-own-IP

- README.md
> Fix link to Control Plane Load Balancing in README.md

- TESTS.md
Document requirements for end-to-end tests. Currently, this is how I do the tests manually. With a clear list in a shared space, we should be able to plan towards automating them as well.
> document requirements for e2e tests

- README.md
> Update README to reflect current control loop

- metal/config.go
The only way to override annotations is using env. The fix also
simplifies config param overriding
> Fix reading of annotation names from config file

- metal/cloud.go
- metal/config.go
- metal/config_test.go
> use env variables when --cloud-config is omitted

- go.mod
- go.sum
bump packet-api-server
bump x/exp
Signed-off-by: Chris Privitere <23177737+cprivitere@users.noreply.github.com>
> Update go Dependencies

- CODE-OF-CONDUCT.md
- LICENSE
- OWNERS
- OWNERS_ALIASES
- RELEASE.md
- SECURITY.md
- SECURITY_CONTACTS
This is a first attempt to get our docs in line with the [Kubernetes Templates](https://github.com/kubernetes/kubernetes-template-project/blob/main/README.md) as part of our effort to get the project migrated to kubernetes-sigs.
> doc: Update docs to be inline with templates

- metal/controlplane_load_balancer_manager.go
Per the CPEM docs, we expect that the LoadBalancer service created by CPEM for the control plane should, by default, have a `port` that matches the port on which `kube-apiserver` is listening, and if the user provided a non-zero value for `apiServerPort`, the LoadBalancer service will use that port.
However, the CPEM reconcilers for both EMLB- and EIP-based control plane load balancing did not actually write the correct `port` values into the Load Balancer service object.
This updates the EMLB reconciler so that:
- By default, the `targetPort` for `default/kubernetes` is written to the `port` for the control plane load balancer service; this is done because the `port` for `default/kubernetes` is `443`
- If `apiServerPort` is non-zero, that value is written into the `port` for the control …
> fix: use the correct external port for control plane LBs

- README.md
Update the primary README.md
* Remove references to support tiers
* Fix all issues markdownlint found
> docs: Remove references to support tiers from README and fix markdown linting issues

- OWNERS_ALIASES
I haven't really maintained this in a very long time. Removing myself from the list.
> Remove deitch as owner

- OWNERS_ALIASES
- Update SIG Cloud Provider Leads to the current list
- Remove cprivitere as I no longer work at Equinix or manage this project.
> feat: Update OWNERS_ALIASES File
